#pragma config(StandardModel, "EV3_REMBOT")
//!!Code automatically generated by 'ROBOTC' configuration wizard               !!//

task main()
{
	datalogClear();

	resetMotorEncoder(leftMotor);
	resetMotorEncoder(rightMotor);

	// This loops makes the robot go forward until the distrace between the robot and the wall is 10 
	while(getUSDistance(sonarSensor)>10)
	{
		int leftEncoder=getMotorEncoder(leftMotor);
		int rightEncoder=getMotorEncoder(rightMotor);

		// this If statement checks if the left wheel has rotated more / great encoder value than the right wheel
		if(leftEncoder-rightEncoder >0)
		{
			//Drift left
			setMotorspeed(leftMotor,18);
			setMotorSpeed(rightMotor,20);
		}
		// this checks if the right wheel has a greater encoder value than the left
		else if(leftEncoder-rightEncoder<0)
		{
			//Drift right
			setMotorSpeed(leftMotor,20);
			setMotorSpeed(rightMotor,18);
		}
		// We want left & right motor encoder values to be exactly equal in order for the robot to move in a straight line
		// That is why in this else statement we are making setting the speed for each motor same and are not making the robot drift
		else
		{
			setMotorSpeed(leftMotor,20);
			setMotorSpeed(rightMotor,20);
		}
		// this code segment is Used for  datalog to start.
		// In this the data logging is done using the color sensor.
		datalogDataGroupStart();
		datalogAddValue(0,getColorReflected(colorSensor));
		datalogDataGroupEnd();
		wait1Msec(10);
	}

}
